CREATE TABLE audit_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    sql_query TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);